development:
  adapter: postgresql
  database: database_name
  username: db_username
  password: db_password
  host: localhost

test:
  adapter: postgresql
  database: database_name
  username: db_username
  password: db_password
  host: localhost

production:
  adapter: postgresql
  database: database_name
  username: db_username
  password: db_password
  host: localhost